config/routes.rb
Rails.application.routes.draw do
  
  # public path for categories
  resources :categories, only: [:show]
  # public path for pages without slugs
  resources :pages, only: [:show]

  # create paths ../admin/pages
  namespace :admin do
    resources :pages
    resources :categories
  end
  
  # loop through each page (that has a slug) and create route based on their slug
  Page.where.not("slug", nil).all.each do |page|
    get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end
  
  # site root routed with "root"
  root 'welcome#index'

  
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :pages
end

app/models/page.rb
class Page < ActiveRecord::Base
    belongs_to :category
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
  
    # GET /categories
    # GET /categories.json
    def index
      @categories = Category.all
    end
  
    # GET /categories/1
    # GET /categories/1.json
    def show
    end
  
    # GET /categories/new
    def new
      @category = Category.new
    end
  
    # GET /categories/1/edit
    def edit
    end
  
    # POST /categories
    # POST /categories.json
    def create
      @category = Category.new(category_params)
  
      respond_to do |format|
        if @category.save
          format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /categories/1
    # PATCH/PUT /categories/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to admin_categories_path, notice: 'Category was successfully updated.' }
          format.json { render :show, status: :ok, location: @category }
        else
          format.html { render :edit }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /categories/1
    # DELETE /categories/1.json
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def category_params
        params.require(:category).permit(:name)
      end
  end
end

app/controllers/admin/pages_controller.rb
module Admin

  class PagesController < ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]
  
    # GET /pages
    # GET /pages.json
    def index
      @pages = Page.all
    end
  
    # GET /pages/1
    # GET /pages/1.json
    def show
    end
  
    # GET /pages/new
    def new
      @page = Page.new
    end
  
    # GET /pages/1/edit
    def edit
    end
  
    # POST /pages
    # POST /pages.json
    def create
      @page = Page.new(page_params)
  
      respond_to do |format|
        if @page.save
          format.html { redirect_to admin_page_path(@page), notice: 'Page was successfully created.' }
          format.json { render :show, status: :created, location: @page }
        else
          format.html { render :new }
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /pages/1
    # PATCH/PUT /pages/1.json
    def update
      respond_to do |format|
        if @page.update(page_params)
          format.html { redirect_to admin_page_path(@page), notice: 'Page was successfully updated.' }
          format.json { render :show, status: :ok, location: @page }
        else
          format.html { render :edit }
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /pages/1
    # DELETE /pages/1.json
    def destroy
      @page.destroy
      respond_to do |format|
        format.html { redirect_to admin_pages_url, notice: 'Page was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_page
        @page = Page.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def page_params
        params.require(:page).permit(:title, :body, :slug, :category_id)
      end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    # find category by its id, and also the pages associated with that category
    def show
        @category = Category.includes(:pages).find params[:id]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def show
        @page = Page.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # display correct page url
    # if page slug exists, display slug
    # otherwise, display page id
    def url_for_page page
        root_path + if page.slug.present?
            page.slug
        else
            "pages/#{page.id}"
        end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/categories/_form.html.haml
= form_for [ "admin", @category ] do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/admin/categories/edit.html.haml
= render 'layouts/nav'
%h1 Editing category

= render 'form'


= link_to 'Back', admin_categories_path

app/views/admin/categories/index.html.haml
= render 'layouts/nav'
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= link_to 'Show', admin_category_path(category)
        %td= link_to 'Edit', edit_admin_category_path(category)
        %td= link_to 'Destroy', admin_category_path(category), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_admin_category_path

app/views/admin/categories/new.html.haml
= render 'layouts/nav'
%h1 New category

= render 'form'

= link_to 'Back', admin_categories_path

app/views/admin/categories/show.html.haml
%p#notice= notice
= render 'layouts/nav'
%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_admin_category_path(@category)
\|
= link_to 'Back', admin_categories_path

app/views/admin/pages/_form.html.haml
= form_for [ "admin", @page] do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :category_id
    = f.select :category_id, Category.all.map { |category| [category.name, category.id] }, class: "form-control"
  .actions
    = f.submit 'Save'

app/views/admin/pages/edit.html.haml
= render 'layouts/nav'
%h1 Editing page

= render 'form'

= link_to 'Show', admin_page_path(@page)
\|
= link_to 'Back', admin_pages_path

app/views/admin/pages/index.html.haml
= render 'layouts/nav'
%h1 Listing pages

%table
  %thead
    %tr
      %th Title
      %th Body
      %th Slug
      %th
      %th
      %th

  %tbody
    - @pages.each do |page|
      %tr
        %td= page.title
        %td= page.body
        %td= url_for_page page
        %td= link_to 'Show', admin_page_path(page)
        %td= link_to 'Edit', edit_admin_page_path(page)
        %td= link_to 'Destroy', admin_page_path(page), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Page', new_admin_page_path

app/views/admin/pages/new.html.haml
= render 'layouts/nav'
%h1 New page

= render 'form'

= link_to 'Back', admin_pages_path

app/views/admin/pages/show.html.haml
= render 'layouts/nav'

%p
  %b Title:
  = @page.title
%p
  %b Body:
  = @page.body
%p
  %b Slug:
  = @page.slug

= link_to 'Edit', edit_admin_page_path(@page)
\|
= link_to 'Back', admin_pages_path

app/views/categories/show.html.haml
// public path for category
= render 'layouts/nav'
%h1 Category: #{@category.name}
// for each page in category, include page title, timestamp, and body contents
-@category.pages.each do |page|
    %article.clearfix
        %h2=link_to page.title, url_for_page(page)
        %p.text-muted=page.created_at.to_formatted_s :long
        =page.body.html_safe
    %hr    

app/views/layouts/_nav.html.haml
%li
    =link_to 'Pages', admin_pages_path
%li
    =link_to 'Categories', admin_categories_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/pages/show.html.haml
// public path for page
= render 'layouts/nav'
%h1= @page.title
%p= time_ago_in_words @page.created_at

= simple_format @page.body